### ISSUE TITLE
[BUG] Time-Sensitive: Location in code to change "Microphone Unmute" icon

### ISSUE THREAD

**Issue by geotraveler** [AgoraIO/Agora-WordPress#101]
**Describe the bug**

Hi there,

I know one of the workarounds Agora added for the audio issues is to display a grey mute icon on the video and then users have to tap on the video to unmute in their browsers (mostly a Safari issue).

Can you please point us to where in the code this icon is being displayed? We would like to change it so it's more visible (red background, etc) as well as add the following text - "TAP TO UNMUTE" - so it is clearly legible and visible for the user.

Please advise.
Thanks

Lola

**Comment by digitallysavvy** [comment]
The mute icon is displayed here 
https://github.com/AgoraIO/Agora-WordPress/blob/192507a0781ee5cd82a45cdc632ea5936a60ec72/public/js/wp-agora-io-public.js#L398

Instead of modifying the icon I would suggest creating a new div with the message you want
```javascript
    remoteStream.play('agora_remote_' + streamId, function(err){
      if (err && err.status !== "aborted"){
        console.log('Remote stream:' + streamId + ' failed to autoplay. Playing muted. Tap <video> container to enable audio.' );

         // show the icon/message

        remoteStream.stop();      
        remoteStream.play('agora_remote_' + streamId, { muted: true });
        // The playback fails. Guide the user to resume the playback by clicking.            
        document.getElementById(streamId + '_container').onclick = playWithAudio; 
        function playWithAudio() {
          console.log('Attempting to play remote stream:' + streamId + ' with audio after user interaction' );
          remoteStream.stop();
          remoteStream.play('agora_remote_' + streamId, { muted: false });
          document.getElementById(streamId + '_container').removeEventListener('click', playWithAudio)
 
         // hide the icon/message

        }     
      }
    });

```

**Comment by geotraveler** [comment]
Thanks so much Hermes!
Can you please share a bit more code on how to explicitly do this? We don't want to break anything.
The problem is that the icon is not very legible (light gray). We want it to be more prominent (white on a red background) with white text that says "tap to unmute"

**Comment by digitallysavvy** [comment]
This issue has been addressed as part of the v3 update.
