### ISSUE TITLE
How to Broadcast?

### ISSUE THREAD

**Issue by nickburrett** [AgoraIO/Agora-WordPress#102]
I am still struggling with this problem from [January](https://github.com/AgoraIO/Agora-WordPress/issues/99#issuecomment-767107074).

You previously mentioned:

> In the image if you take a look at the people icon in the upper left of the Agora window, you'll notice that the number 2 next to the icon, this means two users are in the channel that are set up to broadcast streams, and in this case the local user has their video muted or disabled.

The number is (1) until a guest joins, but then it becomes (2).  As this is supposed to be a broadcast rather than a communication I am not sure why this is happening?

The guest doesn't have any wordpress credentials, so why would this occur?

**Comment by digitallysavvy** [comment]
The number in the upper left of the Agora window represents the number of people in the channel, regardless of ability to broadcast.

If you are in a communication channel then all of the people in the channel can broadcast a stream. If its a broadcast channel, then only the designated users can broadcast their stream. Regardless of channel type, the user count will reflect the number of users (logged in or not logged in) who can see the video stream.

If you wish to limit access to only users that are logged in, then this is not a feature provided directly by the Agora Video for WordPress plugin, you have to use a 3rd party plugin to your WP installation.
