### ISSUE TITLE
[BUG] Toggle fullscreen does not work on iPhone Safari 

### ISSUE THREAD

**Issue by ottverse** [AgoraIO/Agora-WordPress#104]
**Describe the bug**
I integrated the latest plugin into WordPress 5.7, and I successfully tested a broadcast stream on desktops/laptop browsers. But when I opened the stream on my iPhone, the toggle button doesn't work. You can test this even on https://demo.wpagoravideo.com/index.php/full-screen-comm/ - pressing the full-screen icon does nothing. 

**To Reproduce**
1. Go to a broadcast stream on an iPhone's browser - either Safari.
2. Click on the white toggle button
3. The video does not fill the screen.

**Expected behavior**
When the white full-screen button on the top-right is pressed, the video should fill the screen. 

**Smartphone (please complete the following information):**
 - iPhone8
 - iOS14.4
 - Safari
 
Please let me know if you need further clarification. Thank you

**Comment by digitallysavvy** [comment]
@ottverse thanks for your interest in the Agora Video for WordPress plugin. Unfortunately this feature is not currently supported by iOS Safari, for this reason we have included the full page template which is meant to mimic the full screen mode for Safari.
