### ISSUE TITLE
[FEATURE] Is there any way to create dynamic channel in wordpress?

### ISSUE THREAD

**Issue by Jazzykhan** [AgoraIO/Agora-WordPress#106]
Hi, what i want to do is somehting like this.

mywebsite.com/agora(page)?=channel=123
now when two users click on this link they both join to same channel and i dont want it to limit to 123 i can make as many as i want is it possible?
thanks

**Comment by digitallysavvy** [comment]
When creating issues please use the provided templates. Any issues that do not use the provided templates will be closed.
