### ISSUE TITLE
[BUG] cannot live on wordpress

### ISSUE THREAD

**Issue by fahreza007** [AgoraIO/Agora-WordPress#127]
**Describe the bug**
After download the plugin i have issue on the browser cannot live, i follow the documentation for wordpres but didn't work. Am i missing something? 

After install plugin and setting with console agora, why cannot live as host and listener?

Please help me.
Thankyou.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome]
 - Version [e.g. 3.0.1]
 - Xampp 7.4
 - Wordpress 6.0.2

**Smartphone (please complete the following information):**
 - Device: [e.g. Oppo]
 - OS: [e.g. iOS10]
 - Browser [e.g. stock browser]
 - Version [e.g. 3.0.1]

**Additional context**
![image 1](https://user-images.githubusercontent.com/11717937/192181645-57eba050-f2c8-47f9-a52e-e6e59c3c386b.png)
![image 2](https://user-images.githubusercontent.com/11717937/192181647-b8192899-7d74-4156-9d10-c7168759dc24.png)
![image 3](https://user-images.githubusercontent.com/11717937/192181650-a70c99cb-897e-4901-876c-87ee13046ee8.png)

**Comment by digitallysavvy** [comment]
can you please share a screenshot of the Agora Plugin Settings? It should look something like this:
![image](https://user-images.githubusercontent.com/6816583/192384587-22889d92-3361-4699-abf1-f33819fdc806.png)


reference: [https://github.com/AgoraIO/Agora-WordPress/wiki/Setup](https://github.com/AgoraIO/Agora-WordPress/wiki/Setup)

**Comment by fahreza007** [comment]
This sir.

![image 4](https://user-images.githubusercontent.com/11717937/192422765-5c382675-1b5d-4a4f-8587-eb353b46beee.png)

**Comment by fahreza007** [comment]
Bug solved, missing on css

**Comment by digitallysavvy** [comment]
@fahreza007 can you please share what CSS properties were missing, or how you solved this issue? This will help other users and if applicable can add them to the build or add this as part of the FAQ in-case it was some other CSS overwriting the defaults.

**Comment by fahreza007** [comment]
With default theme on wordpress, i used theme hello elementor.
Add custom css :
.agora-footer {
    display: block !important;
}
