### ISSUE TITLE
Special Build needed

### ISSUE THREAD

**Issue by digitallysavvy** [AgoraIO/Agora-WordPress#128]
@EkaanshArora in order to update the Agora SDK its best to request a special build from Derek that adds the tag for WordPress otherwise it's impossible to track usage and causes issues for the support team as they won't realize the user is on WordPress.

**Comment by EkaanshArora** [comment]
Hi Hermes, I had flagged this to the rest of team that updating the sdk would break usage tracking. We’re evaluating how to proceed with the wordpress plugin, I’ll update with a special build once the rest of the team is on board. Thank you!

**Comment by digitallysavvy** [comment]
Sounds good. If it helps, in the past I worked with the support team to put in the request with engineering and there should be a completed ticket within Jira that will help with explaining the business case.
