### ISSUE TITLE
Scalable Multi Users UI [FEATURE]

### ISSUE THREAD

**Issue by digitallysavvy** [AgoraIO/Agora-WordPress#48]
**Is your feature request related to a problem? Please describe.**
Currently the plugin supports up to 17 users within a single channel (communication/broadcast) but the current UI templates are not visually appealing and do not scale well. 

**Describe the solution you'd like**
We need to implement UI templates that scale from 1 to 17 broadcasters in both broadcasting and communication channels.

**Describe alternatives you've considered**
Currently a developer has to create their own UI templates.

**Comment by digitallysavvy** [comment]
# Mock ups #
The designs below are representative of the UI templates we want to build as part of this enhancement.

## Broadcasting ##

![A_MGFjZjlkZDY2YjhlM2JmOQ-vAjz0vsmUa1M5F6OupYapfcyguIotHt-NIM-jTYD-rdFvsE01uLwefhaqH6yZguxMkXv0CKDmfbuFXpo_tV7ar2puFj0h_70__5moHe39](https://user-images.githubusercontent.com/6816583/79016194-5acf2300-7b3c-11ea-92b9-5b2a936cf3c8.jpeg)

![A_MGFjZjlkZDY2YjhlM2JmOXEI0Kp-GNzXRTEnK6TjDWxx5jiMSzdO22gMQuBZ5jtiQvjpfEUiPg5LYPqdR_2LpihT-ef5ieJifAbK93d5NRRKg3xMB5MX_tAfrEARd2Xw](https://user-images.githubusercontent.com/6816583/79016201-5c005000-7b3c-11ea-8d0c-b86a179b6792.jpeg)

## Communication ##
![A_MGFjZjlkZDY2YjhlM2JmOYrcaH_x9LFHYhkhCdOCFpFcX_juRIUCvUkGyYhTElCThV7UksadssqkzQmMfL9K_JUuDdp8-anUaVgUSG2h_GKW2zFWSrTjwETmlzPLpSmi](https://user-images.githubusercontent.com/6816583/79016204-5d317d00-7b3c-11ea-93ee-de325c522988.jpeg)
![A_MGFjZjlkZDY2YjhlM2JmOcJLSG3uF64BuDmkOakd05G9L0fToo9GDZ5CF1UPaBpTw56EdFYjAo-cb4K4yH0KCOZeTPZGmZIqzJBjRLtzuVLLdaO5OEeMxXXpHMUxPiab](https://user-images.githubusercontent.com/6816583/79016192-5a368c80-7b3c-11ea-980f-a200baec5506.jpeg)
![A_MGFjZjlkZDY2YjhlM2JmOW1hHWtuWeVPWuHTqK5IRRYYKLYCU9EQiroDc3WV5P4t-1FtfSTbdQvC2oDPu6NpH1QRg0e2avmxc09Q5zLZCjW_N2a_leahx_6fpvc6u9XY](https://user-images.githubusercontent.com/6816583/79016199-5c005000-7b3c-11ea-9f8e-09502cd142a9.jpeg)
![A_MGFjZjlkZDY2YjhlM2JmOQgKKKfWT-Pl-AxZBRFdmFrDjv1n-B8p-9YiLorcGsbJzFeZFGQsgGwRwkH7VSjRiHQYeLMxhH-cQSNj2utiQTYOEqz6LTDxdcB5MkZj1vEU](https://user-images.githubusercontent.com/6816583/79016196-5b67b980-7b3c-11ea-929f-3ee45cf0e270.jpeg)
![A_MGFjZjlkZDY2YjhlM2JmOaOtVeV28eFpAwYKusuj46cMxygLA7NqwNcdErak7IFt2r2qq7oeuvQUGbB-VLhCJM6rhWdQkqfgHqs6mAtZbbj_LzKPzYzyMII1Msk0Z5Vl](https://user-images.githubusercontent.com/6816583/79016187-573b9c00-7b3c-11ea-852a-d588f3977ee9.jpeg)

![A_MGFjZjlkZDY2YjhlM2JmOc1sUeCgp1PvJ9b8ImVgY0kzKOuIQblpgRA-eli_XOHNw4t6mth3D3xNU813RyccwVC0J7EDN49Y5pjajZDF29lo0A2aYx-ZftpZfcguBe2r](https://user-images.githubusercontent.com/6816583/79016191-59055f80-7b3c-11ea-9182-566d6b8cb16d.jpeg)

**Comment by jalamprea** [comment]
@digitallysavvy  In the Broadcasting mode, there is an icon for Participants but it is not in the Communication mode. So it means that it's needed to identify users connected only on Broadcast mode? If so, it's needed to restrict the audience to authenticated users only?
Also, there is any proposal for the design of the Participants List? or just any modal window with the participants' names?

**Comment by digitallysavvy** [comment]
@jalamprea i think we can include it for broadcasting as well, but we will need to use an RTM channel to count users.
