### ISSUE TITLE
MOBILE UI [FEATURE]

### ISSUE THREAD

**Issue by digitallysavvy** [AgoraIO/Agora-WordPress#50]
**Is your feature request related to a problem? Please describe.**
Currently the WordPress plugin is does not properly adjust for mobile screens.

**Describe the solution you'd like**
Create a mobile UI for users using the WP plugin on mobile. 

**Additional context**
We should also show a message on mobile browsers that are not supported

**Comment by digitallysavvy** [comment]
# Mock ups #
The designs below are representative of the UI templates we want to build as part of this enhancement.

## Communication ##
![A_MGFjZjlkZDY2YjhlM2JmOThQIiykgMvaVOpaMyWqPqgaRtDx7r3PwDCc9BLGcljtWs5ycH3lErk0YLi_TLo5FKHfwwHgm1_QhjedGvcraP7TwL0BSfQ6Aw1O0J1jd4Q3](https://user-images.githubusercontent.com/6816583/79023765-1731e480-7b4f-11ea-8328-c8a61c42466e.jpeg)
![A_MGFjZjlkZDY2YjhlM2JmOSAD7VUTtJd1zrZ-jyjnUmW_ZGPOZF9UHbunC_5_8w8AABnS3Rp5FOMZ3_YF2xvTl4X8rMDMA4ky1e6TcIPdFdb5-Dj_MrJ4shC4EvrSIWuW](https://user-images.githubusercontent.com/6816583/79023771-1a2cd500-7b4f-11ea-8179-9b669ff01961.jpeg)
![A_MGFjZjlkZDY2YjhlM2JmOanPZmadF2m_QrKfOhXe-oNXgYO698YYdAe5iAUsWGRNZYCQmVzsghnTJ6H3Lnw2U5a_-_cNDaw-2IeQjF-SfIyTcthzmyU44AQF-6GbREdl](https://user-images.githubusercontent.com/6816583/79023775-1dc05c00-7b4f-11ea-950d-069a22957eaa.jpeg)
![A_MGFjZjlkZDY2YjhlM2JmOZ2PuSOPtmN9ULhVR5zztw5B9MiLZK-4dwn54TWljohVKvtag9eh4s03J9MSafdmDwCR1uTPKNr6wXbVhffVHRTOjANgwNlmXy4UkjduZuB1](https://user-images.githubusercontent.com/6816583/79023779-20bb4c80-7b4f-11ea-9e87-67af3eb21e9a.jpeg)

## Broadcasting ##
![A_MGFjZjlkZDY2YjhlM2JmOYhBvYHtM0DzsIc2aw6XCeYJEhVCcJaKGGcaOSk0VWEH5c6dBuZJhQP46E_pz2HCH5IPiFD2pSH6Y_W0EP3DX0JItJTkE4BLyxYbGansEG4Y](https://user-images.githubusercontent.com/6816583/79023833-45afbf80-7b4f-11ea-87c3-d90dda358714.jpeg)
![A_MGFjZjlkZDY2YjhlM2JmOZAfy3_vMNc8x5OvCVzGaUfwNDidDu88R-qlYj1yVAL2E-iZBjDLKYtfwzJYhOHquYfMw0I4XpFAD7mTCNz5Vl3hm2bOw-X3JxAFkSyCv14m](https://user-images.githubusercontent.com/6816583/79023840-48aab000-7b4f-11ea-94af-88a4ffd0f6f2.jpeg)

**Comment by ottverse** [comment]
Hi @digitallysavvy, is there a way I can access this feature? I tried the Agora plugin on a mobile phone and it doesn't display fullscreen like your mockups. Also, the chat is not overlayed with the video. When I click on chat, it actually pushes the video up and then I have to scroll after sending a chat message.

Please let me know. Thank you.

**Comment by geotraveler** [comment]
I'm following this thread as well as I would love those UI templates too (plus we're having the same issue with the chat).
Thanks1
