### ISSUE TITLE
Recording Settings [FEATURE]

### ISSUE THREAD

**Issue by RahKapoor** [AgoraIO/Agora-WordPress#55]
**Describe the bug**
Recording is done in Portrait mode

**To Reproduce**
1. Setup a Broadcast
2. Click on the record button when the broadcast is live
3. Check Amazon S3
4. It recorded the landscape video in portrait mode.

**Expected behavior**
It should be landscape

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  81.0.4044.113 (Official Build) (64-bit)

**Additional context**
Is this a simple fix?

**Comment by digitallysavvy** [comment]
@RahKapoor I think the best fix would be to expose the recording layout settings to the admin because this is a matter of preference. We are also looking to add support for multi-host/user broadcasts so we need to let the admin choose the layout that fits their project requirements.

**Comment by digitallysavvy** [comment]
This has been resolved as part of the v3 update.
