### ISSUE TITLE
[BUG] Hosts cannot see Broadcast viewer's chat questions

### ISSUE THREAD

**Issue by geotraveler** [AgoraIO/Agora-WordPress#86]
**Describe the bug**

With the Broadcast channel, the hosts can see their own chats, but when a Broadcast viewer types their name and tries to connect in the chat to type their questions, the hosts cannot see the viewers.

**To Reproduce**

To Reproduce

Login first at https://marketplace.localpurse.com/login

**Host 1**

Username: -
Password: -

**Host 2**

Username: -
Password: -

Then go to this link - https://marketplace.localpurse.com/intrepid/morocco

**Incognito - Broadcast viewer**

Go directly to this link - https://marketplace.localpurse.com/intrepid/morocco

**Expected behavior**

The hosts need to be able to read the Broadcast viewer's question.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version : 87

**Comment by digitallysavvy** [comment]
After testing I don't see any of the Ui elements for the chat. Is it possible that the CSS in the theme is causing UI elements to become hidden?

**Comment by geotraveler** [comment]
We turned off the chat in the Agora global settings for now. It was giving us UI issues in horizontal view on the mobile phone. Even though we modified the CSS.

**Comment by digitallysavvy** [comment]
Was the issue only on mobile or on desktop as well?

**Comment by geotraveler** [comment]
Only on mobile when turned horizontal which is how guides will use the phone on gimbals.

**Comment by digitallysavvy** [comment]
This issue has been addressed as part of the v3 update.
