### ISSUE TITLE
[BUG] Chat window is cropped off -Horizontal mobile view

### ISSUE THREAD

**Issue by geotraveler** [AgoraIO/Agora-WordPress#89]
**Describe the bug**

The chat window is cropped off at the top so the user can't close it when viewing on a mobile phone (horizontal view)

See right side of attached screenshot.
![IMG_8263](https://user-images.githubusercontent.com/74770503/100603084-f0563780-3304-11eb-9479-52e254785dce.jpg)

**Comment by digitallysavvy** [comment]
This is a CSS issue specific to your implementation and theme, you will need to adjust this yourself to best fit your theme. 

![819FDA78-FF8D-4106-B5C4-4CBA172A09E8](https://user-images.githubusercontent.com/6816583/100615543-ba558b00-32e5-11eb-84e2-eacb6a59922a.png)

**Comment by geotraveler** [comment]
Hi there,
That is the vertical view. Have you tried the horizontal view of the mobile phone?
Please do so. You will see the issue.
Thanks

**Comment by geotraveler** [comment]
Turn the phone to its side and view it. You should see the same issue with the chat.

**Comment by digitallysavvy** [comment]
In horizontal mode it appears a bit above the video but the use can still scroll up to view the top of the chat window. 

The chat window height can be controlled with CSS to fix any scale issue. 


![5BA94CD7-D6C9-4401-BA8E-1F1E8A8AFFC9](https://user-images.githubusercontent.com/6816583/100964307-57870e00-34f6-11eb-9d8c-0feeaeaf2275.png)
