### ISSUE TITLE
[BUG] Several Black Rectangles Appearing 

### ISSUE THREAD

**Issue by geotraveler** [AgoraIO/Agora-WordPress#91]
**Describe the bug**

This note came from BigStep who has been working with us to extend the plugin after they troubleshooted the root cause:

"The issue is coming when there is an interruption in the internet connection, i.e., if the user's internet connection is affected then the peer leaves, in the plugin the div is not getting closed. This issue is in the core plugin."

**To Reproduce**

Several hosts can connect to a broadcast. When one of them drops (or internet disconnects), the black rectange keeps hanging and sometimes when the host reconnects, they are hidden behind the black rectangle and a tiny bit visible underneath. 

For example 3 hosts, A, B, C - If C gets disconnected and reconnects, then there are 4 videos, with one black rectangle where C used to be and the new C video. If it happens again to C, then there are 5 videos with two black rectangles, and it goes on and on.

**Expected behavior**
When a host leaves, only the remaining hosts should remain on the screen. Not a black rectangle where the host was before they left or were abruptly disconnected.

**Screenshots**
See attached screenshots

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Safari, Edge

![Agora Bug 1](https://user-images.githubusercontent.com/74770503/101371222-ca073d80-38aa-11eb-9ddd-7b4efe242a52.png)
![Agora Bug](https://user-images.githubusercontent.com/74770503/101371234-cc699780-38aa-11eb-9ebd-acf322556e00.png)

**Comment by digitallysavvy** [comment]
It looks like this is a side effect of adding the logic in #85 to keep the channel from closing if the broadcaster drops out due to poor connection. 

There needs to be some logic added to clean up the UI if broadcaster leaves the channel so when they rejoin the Ui displays as expected.

**Comment by geotraveler** [comment]
That is what BigStep is working on for us, but isn't this something you would need to add to the base functionality of the core plugin?

**Comment by digitallysavvy** [comment]
Yes this would be a core functionality to the plugin.

**Comment by digitallysavvy** [comment]
v2.0.7 resolves this issue
