### ISSUE TITLE
[BUG] Problems persist with Chat Window

### ISSUE THREAD

**Issue by geotraveler** [AgoraIO/Agora-WordPress#94]
**Describe the bug**

When a mobile phone is turned horizontally, the chat window still keeps getting cut off. We've tried to fix this with CSS but to no avail. The other issue is that the Chat window is duplicating messages that are being typed.

Please see both attached screenshots.

**Expected behavior**
The Chat window shouldn't be cut off and should only display messages once.

**Screenshots**
![IMG_9350](https://user-images.githubusercontent.com/74770503/104566345-c60ad000-564d-11eb-824a-1b8635296967.PNG)
![IMG_9352](https://user-images.githubusercontent.com/74770503/104566350-c7d49380-564d-11eb-82e4-c05d3f34112b.PNG)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone
 - Browser: Safari

**Comment by digitallysavvy** [comment]
This issue has been addressed as part of the v3 update. There is now a setting within the Agora Plugin Settings page to adjust the placement of the chat window.
