### ISSUE TITLE
Plugin doesn't capture entire camera?

### ISSUE THREAD

**Issue by nickburrett** [AgoraIO/Agora-WordPress#99]
I am using OBS virtual camera, which seems to work fine with Zoom.

Why doesn't the plugin capture my whole virtual camera screen, it only seems to catch part?
https://1drv.ms/u/s!Ap_XGPl2MJg7gxcmLbpOX6Uf6e7F?e=pSuX8h

Why does the player only show half of the captured image?
https://1drv.ms/u/s!Ap_XGPl2MJg7gxj26Ff34q4iFAVJ?e=MeVIh6

**Comment by digitallysavvy** [comment]
> Why doesn't the plugin capture my whole virtual camera screen, it only seems to catch part?
https://1drv.ms/u/s!Ap_XGPl2MJg7gxcmLbpOX6Uf6e7F?e=pSuX8h

This looks like a CSS fill vs fit, have you tried adjusting the CSS?

>Why does the player only show half of the captured image?
https://1drv.ms/u/s!Ap_XGPl2MJg7gxj26Ff34q4iFAVJ?e=MeVIh6
In the image if you take a look at the people icon in the upper left of the Agora window, you'll notice that the number 2 next to the icon, this means two users are in the channel that are set up to broadcast streams, and in this case the local user has their video muted or disabled.

**Comment by nickburrett** [comment]
> This looks like a CSS fill vs fit, have you tried adjusting the CSS?

What CSS would I be adjusting, I would have assumed that if you send a full picture, you expect to receive a full picture in return.  No changes have been made to the plugin, the default values remain intact.

> In the image if you take a look at the people icon in the upper left of the Agora window, you'll notice that the number 2 next to the icon, this means two users are in the channel that are set up to broadcast streams, and in this case the local user has their video muted or disabled.

There is only one user broadcasting and therefore I would expect to see only one full sized image.

**Comment by digitallysavvy** [comment]
> What CSS would I be adjusting, I would have assumed that if you send a full picture, you expect to receive a full picture in return. No changes have been made to the plugin, the default values remain intact.

In the Agora plugin we chose to use the default Agora behavior which crops the video to ensure the video "fills" the div. To avoid this cropping and force all Agora video elements to always "fit" the content within the div use this CSS:

```CSS
.agora .screen-users video{
  object-fit: contain !important;
}
```

You can add this with the WordPress Admin panel, click "Appearance Customize" and then click "Additional CSS" and input the above CSS code into the input field and click "Publish".

> There is only one user broadcasting and therefore I would expect to see only one full sized image.
Within your test is the window on the right side of the screen using the same logged in user as the broadcast?
